// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function OpenDir(arg1) {
  return window['go']['main']['App']['OpenDir'](arg1);
}

export function ProjectInfoList() {
  return window['go']['main']['App']['ProjectInfoList']();
}

export function UpdateWorkspaceRecommendationsIgnore(arg1) {
  return window['go']['main']['App']['UpdateWorkspaceRecommendationsIgnore'](arg1);
}
