// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function OpenDir(arg1:string):Promise<void>;

export function ProjectInfoList():Promise<Array<main.ProjectInfo>>;

export function UpdateWorkspaceRecommendationsIgnore(arg1:Array<main.ProjectInfo>):Promise<void>;
